/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

import org.example.exception.InvalidDiscountException;
import org.example.exception.InvalidDurationException;
import org.example.exception.RentalServiceException;
import org.example.model.RentalTerms;
import org.example.model.Tool;
import org.example.service.RentalService;
import org.example.service.impl.RentalServiceImpl;

public class App {
    // public String getGreeting() {
    //     return "Hello World!";
    // }

    // public static void main(String[] args) {
    //     System.out.println(new App().getGreeting());
    // }

    public static void main(String[] args) {
        RentalService rentalService = new RentalServiceImpl();
        Tool tool = new Tool("LADW","Ladder","Werner", 1.99F,true,true,false);
        rentalService.addTool(tool);
        tool = new Tool("CHNS","Chainsaw","Stihl", 1.49F,true,false,true);
        rentalService.addTool(tool);
        tool = new Tool("JAKR","Jackhammer","Ridgid", 2.99F,true,false,false);
        rentalService.addTool(tool);
        tool = new Tool("JAKD","Jackhammer","DeWalt", 2.99F,true,false,false);
        rentalService.addTool(tool);

        Scanner inputScanner = new Scanner(System.in);

        System.out.println("---------------------------------------------------------\n" +
                "Welcome to the rental service Demo. Within this demo,\n" +
                "---------------------------------------------------------");

        var toolCode = "";
        System.out.print("Please enter the tool code to rent out: ");
        // while(inputScanner.hasNextLine()) {
            toolCode = inputScanner.nextLine();
        // }

        var checkoutDate = "";
        System.out.print("Please enter the date to checkout. Use format (m/d/yy or m/d/yyyy): ");
        // while(inputScanner.hasNextLine()) {
            checkoutDate = inputScanner.nextLine();
        // }

        System.out.print("Please enter the duration you like the rental, in days: ");
        var duration = inputScanner.nextInt();

        System.out.print("Please enter the discount as a whole number representing the percent discount: ");
        var discount = inputScanner.nextInt();

        try {
            RentalTerms agreement = rentalService.checkout(toolCode, checkoutDate, duration, discount);
            System.out.println("Copy of the rental agreement, for your records: \n\n");
            System.out.println(agreement.toString());
        }catch(InvalidDiscountException e) {
            System.out.println("Unfortunately, the discount you provided, " + discount +
                    ", is invalid. Please run the program to try again. Below will be a detailed\n" +
                    "stack trace of the event.");
            e.printStackTrace();
        }catch(InvalidDurationException e) {
            System.out.println("Unfortunately, the rental duration you provided, " +
                    duration + ", is not valid. Please run the program to try again. Below\n" +
                    "will be a detailed stack trace of the event.");
            e.printStackTrace();
        }catch(RentalServiceException e) {
            System.out.println("Unfortunately, it appears that there was an error. Please\n" +
                    "consult the detailed stack trace below for more information.");
            e.printStackTrace();
        }

        inputScanner.close();
        System.out.println("\n\nThank you for trying this rental service!");
    }
}
